import type {Pool} from 'pg'
import type {FastifyInstance} from 'fastify'
import {callCurator} from './planner.js'
const id='xps14-2026-x7-oled-32-1tb'
export async function migratePrices(p:Pool){await p.query(`CREATE TABLE IF NOT EXISTS price_items(id text PRIMARY KEY,title text NOT NULL,target_cents integer NOT NULL,paused boolean NOT NULL DEFAULT false);CREATE TABLE IF NOT EXISTS price_sources(item_id text REFERENCES price_items(id),store text,last_attempt timestamptz,next_run timestamptz NOT NULL DEFAULT now(),status text NOT NULL DEFAULT 'pending',detail text,last_good jsonb,PRIMARY KEY(item_id,store));CREATE TABLE IF NOT EXISTS price_observations(id bigserial PRIMARY KEY,item_id text REFERENCES price_items(id),store text,observed_at timestamptz NOT NULL DEFAULT now(),data jsonb NOT NULL);`);await p.query('INSERT INTO price_items(id,title,target_cents) VALUES($1,$2,280000) ON CONFLICT DO NOTHING',[id,'Dell XPS 14 (2026) · X7 358H · OLED touch · 32 GB · 1 TB']);for(const store of ['bestbuy','dell','microcenter'])await p.query('INSERT INTO price_sources(item_id,store) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,store])}
export async function checkPrices(p:Pool){const c=await p.connect();let locked=false;try{locked=(await c.query('SELECT pg_try_advisory_lock(817361) ok')).rows[0].ok;if(!locked)return;const rows=(await c.query('SELECT s.* FROM price_sources s JOIN price_items i ON i.id=s.item_id WHERE NOT i.paused AND s.next_run<=now() ORDER BY s.next_run LIMIT 1')).rows;for(const r of rows){await c.query("UPDATE price_sources SET last_attempt=now(),next_run=now()+interval '6 hours' WHERE item_id=$1 AND store=$2",[r.item_id,r.store]);try{const data=await callCurator({mode:'price-check',store:r.store}) as {store:string;status:string;detail:string;offers:{condition:string;cents:number;currency:string;eligible:boolean}[]};if(data.store!==r.store||!['verified','blocked','unverified','unmatched'].includes(data.status)||typeof data.detail!=='string'||!Array.isArray(data.offers)||data.offers.some(o=>!Number.isInteger(o.cents)||o.cents<=0||o.currency!=='USD'||!['new','open-box'].includes(o.condition)))throw Error('Invalid result');await c.query('BEGIN');await c.query('UPDATE price_sources SET status=$3,detail=$4 WHERE item_id=$1 AND store=$2',[r.item_id,r.store,data.status,data.detail]);if(data.status==='verified'&&data.offers.length){const observedAt=new Date().toISOString();await c.query('INSERT INTO price_observations(item_id,store,data) VALUES($1,$2,$3)',[r.item_id,r.store,data]);await c.query('UPDATE price_sources SET last_good=$3 WHERE item_id=$1 AND store=$2',[r.item_id,r.store,{...data,observedAt}])}await c.query('COMMIT')}catch{await c.query('ROLLBACK');await c.query("UPDATE price_sources SET status='failed',detail='Browser or retailer unavailable. Last verified prices retained.' WHERE item_id=$1 AND store=$2",[r.item_id,r.store])}}}finally{if(locked)await c.query('SELECT pg_advisory_unlock(817361)');c.release()}}
export function priceRoutes(app:FastifyInstance,p:Pool){
 app.get('/api/v1/prices/snapshot',async()=>({items:(await p.query('SELECT * FROM price_items ORDER BY id')).rows,sources:(await p.query('SELECT * FROM price_sources ORDER BY store')).rows,history:(await p.query('SELECT * FROM price_observations ORDER BY id DESC LIMIT 300')).rows}))
 app.post<{Body:{id:string;targetCents:number;paused:boolean}}>('/api/v1/prices/settings',async(req,reply)=>{const b=req.body;if(typeof b?.id!=='string'||!Number.isInteger(b.targetCents)||b.targetCents<1||b.targetCents>10000000||typeof b.paused!=='boolean')return reply.code(400).send({error:'Invalid settings'});const r=await p.query('UPDATE price_items SET target_cents=$2,paused=$3 WHERE id=$1',[b.id,b.targetCents,b.paused]);return r.rowCount?{saved:true}:reply.code(404).send({error:'Unknown item'})})
 app.post('/api/v1/prices/refresh',async(_req,reply)=>{const r=await p.query("UPDATE price_sources s SET next_run=now() FROM price_items i WHERE s.item_id=i.id AND NOT i.paused AND (s.last_attempt IS NULL OR s.last_attempt<now()-interval '10 minutes')");return reply.code(202).send({queued:r.rowCount,note:r.rowCount?'Price checks queued.':'Paused or checked recently; try again after 10 minutes.'})})
}
