import {useState} from 'react'
import type {Planner,Preparation,Exam,Topic} from './usePlanner'
import {PlannerStatus} from './Projects'
async function post(path:string,data:unknown){const r=await fetch('/api/v1/planner/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error??'Could not connect');return result}
export function PreparationPanel({event,planner:p,onClose}:{event:Exam;planner:Planner;onClose:()=>void}){
 const existing=p.preparations.find(x=>x.event.calendarId===event.calendarId&&x.event.uid===event.uid&&x.event.recurrenceId===event.recurrenceId)
 const key='daymark.study-draft.'+event.calendarId+':'+event.uid+':'+event.recurrenceId
 const [draft,setDraft]=useState<Preparation>(()=>{try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved?.draft?.event?.uid===event.uid)return saved.draft}catch{/* retain accessible server version */}return existing??{id:crypto.randomUUID(),title:event.title,event,startDate:'',status:'active',topics:[],progress:''}})
 const [baseVersion]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(Number.isInteger(saved?.baseVersion))return saved.baseVersion}catch{/* use current revision */}return p.versionOf(existing?.id??'')})
 const [text,setText]=useState(()=>{try{return JSON.parse(localStorage.getItem(key)??'null')?.text??''}catch{return ''}})
 const [session,setSession]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reviewed,setReviewed]=useState(false)
 const update=(next:Preparation,source=text)=>{setDraft(next);setText(source);setReviewed(false);try{localStorage.setItem(key,JSON.stringify({draft:next,text:source,baseVersion}))}catch{setMessage('Browser storage unavailable. Keep this panel open until you save.')}}
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'Could not complete request')}finally{setBusy(false)}}
 const topic=(id:string,patch:Partial<Topic>)=>update({...draft,topics:draft.topics.map(t=>t.id===id?{...t,...patch}:t)})
 const deadline=event.allDay?event.start.slice(0,10):new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(event.start))
 const history=p.actions.filter(a=>a.preparationId===draft.id)
 return <section className="card project-editor preparation-panel" aria-label="Event preparation"><div className="section-heading"><h2>Prepare for {event.title}</h2><button onClick={onClose}>Close preparation</button></div><p className="local-note">Exam: {deadline}. Study actions appear on Home, not as extra calendar events. Preparation ends before exam day.</p><label>Start studying<input type="date" required max={deadline} value={draft.startDate} onChange={e=>update({...draft,startDate:e.target.value})}/></label><label>Preparation status<select value={draft.status} onChange={e=>update({...draft,status:e.target.value})}><option value="active">Active</option><option value="paused">Paused</option></select></label>
 <details open={!draft.topics.length}><summary>Materials and study context</summary><p className="local-note">Upload text-based PDFs, TXT or Markdown (5 MB each). Extracted text stays in this browser draft; reviewed topic notes and progress sync to the backend. Original files are not stored. Scanned PDFs need a text version.</p><label>Upload study material<input type="file" accept=".pdf,.txt,.md" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;void run(async()=>{if(file.size>5*1024*1024)throw Error('Maximum file size is 5 MB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const value of bytes)binary+=String.fromCharCode(value);const result=await post('material',{name:file.name,content:btoa(binary)});if(text.length+result.text.length>100000)throw Error('Combined context exceeds 100,000 characters. Split or shorten it.');update(draft,text+'\n'+result.text);setMessage('Text extracted. Review it below before asking Hermes.')})}}/></label>
 <label>Hermes session ID (optional)<input value={session} onChange={e=>setSession(e.target.value)} placeholder="Exact session ID"/></label><button disabled={busy||!session} onClick={()=>void run(async()=>{const result=await post('session',{sessionId:session});if(text.length+result.text.length>100000)throw Error('Combined context too long. Paste the relevant excerpts instead.');update(draft,text+'\n[Session '+session+']\n'+result.text);setMessage(result.notice)})}>Load selected session excerpts</button>
 <label>Review source text / add topics and context<textarea rows={8} maxLength={100000} value={text} onChange={e=>update(draft,e.target.value)}/></label><p className="local-note">Remove unrelated discussion before extracting. Only this text is sent to the curator. Mentioning a topic does not count as mastering it.</p><button disabled={busy||!text.trim()} onClick={()=>void run(async()=>{const result=await post('extract',{title:event.title,text});update({...draft,topics:result.topics,progress:result.progress});setMessage('Review the proposed topics, estimates and progress below. Nothing is saved to your plan yet.')})}>Extract study outline</button></details>
 {busy&&<p role="status">Working with your selected material…</p>}{message&&<p role="status">{message}</p>}
 <h3>Review preparation sequence</h3><p className="local-note">Each topic can span several days. Include practice and review stages. Estimates are editable; they are not claims about how much you already know.</p>{draft.topics.map((t,i)=><fieldset key={t.id}><legend>Step {i+1}</legend><label>Topic<input value={t.title} maxLength={240} onChange={e=>topic(t.id,{title:e.target.value})}/></label><label>References and definition of done<textarea maxLength={4000} value={t.notes} onChange={e=>topic(t.id,{notes:e.target.value})}/></label><label>Estimated total minutes<input type="number" min={5} max={1800} value={t.minutes} onChange={e=>topic(t.id,{minutes:Number(e.target.value)})}/></label><button onClick={()=>update({...draft,topics:draft.topics.filter(x=>x.id!==t.id)})}>Remove topic</button></fieldset>)}<button disabled={draft.topics.length>=60} onClick={()=>update({...draft,topics:[...draft.topics,{id:crypto.randomUUID(),title:'',notes:'',minutes:45}]})}>Add topic manually</button><label>Known progress and weak areas<textarea maxLength={4000} value={draft.progress} onChange={e=>update({...draft,progress:e.target.value})}/></label><label className="study-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed the topics, estimates and progress.</label><button disabled={busy||!reviewed||!draft.startDate||draft.startDate>=deadline||!draft.topics.length||draft.topics.some(t=>!t.title.trim()||t.minutes<5||t.minutes>1800)} onClick={()=>{if(p.save('preparation',{...draft,event},baseVersion)){try{localStorage.removeItem(key)}catch{/* queued data remains */}onClose()}}}>Save preparation</button><PlannerStatus planner={p}/>
 {history.length>0&&<details><summary>Study history</summary>{history.map(a=><p key={a.id}>{a.date} · {a.title} · {a.completed?'Completed':a.dismissed?'Dismissed':'Not completed'}{a.feedback?' · '+a.feedback:''}</p>)}</details>}<p className="local-note">Hermes chooses the next daily steps from remaining topics and your available time. Missed work is reconsidered, not stacked on top of tomorrow. Completed and edited cards stay in history. Moving this exam updates its target on the next calendar sync; a missing event pauses generation.</p></section>
}
