import {test,expect} from '@playwright/test'
test('event creation is queued offline and survives reload',async({page})=>{
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{authenticated:true,configured:true}}))
 await page.route('**/api/v1/calendar/snapshot',r=>r.fulfill({json:{calendars:[{id:'fixture',name:'Test calendar'}],events:[],lastSuccess:new Date().toISOString()}}))
 await page.route('**/api/v1/calendar/changes',r=>r.abort())
 await page.goto('http://127.0.0.1:5173/')
 await page.getByRole('button',{name:'New event',exact:true}).click()
 await page.setViewportSize({width:375,height:900})
 await page.getByLabel('Event title',{exact:true}).fill('Offline test event')
 await page.screenshot({path:'test-results/calendar-editor-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Save event',exact:true}).click()
 await expect(page.getByText('Offline test event',{exact:true})).toBeVisible()
 await page.reload()
 await expect(page.getByText('Offline test event',{exact:true})).toBeVisible()
 let submitted=0
 await page.unroute('**/api/v1/calendar/changes')
 await page.route('**/api/v1/calendar/changes',r=>{submitted++;return r.fulfill({json:{saved:true}})})
 await page.evaluate(()=>window.dispatchEvent(new Event('online')))
 await expect.poll(()=>submitted).toBe(1)
 await expect(page.getByText('Offline test event',{exact:true})).toHaveCount(0)
})

test('conflicting queued edits are retained and not retried silently',async({page})=>{
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{authenticated:true,configured:true}}))
 await page.route('**/api/v1/calendar/snapshot',r=>r.fulfill({json:{calendars:[{id:'fixture',name:'Test calendar'}],events:[],lastSuccess:new Date().toISOString()}}))
 let attempts=0
 await page.route('**/api/v1/calendar/changes',r=>{attempts++;return r.fulfill({status:409,json:{error:'changed'}})})
 await page.goto('http://127.0.0.1:5173/')
 await page.getByRole('button',{name:'New event',exact:true}).click()
 await page.getByLabel('Event title',{exact:true}).fill('Conflicting test draft')
 await page.getByRole('button',{name:'Save event',exact:true}).click()
 await expect(page.getByText('Changed in Nextcloud.',{exact:false})).toBeVisible()
 await page.reload()
 await expect(page.getByText('Conflicting test draft',{exact:true})).toBeVisible()
 await page.evaluate(()=>window.dispatchEvent(new Event('online')))
 await expect.poll(()=>attempts).toBe(1)
 await page.getByRole('button',{name:'Discard draft',exact:true}).click()
 await expect(page.getByText('Conflicting test draft',{exact:true})).toHaveCount(0)
})
