import { test, expect } from '@playwright/test'

test('local task editing, priority, search, delete and undo survive refresh', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173/')
  await page.getByLabel('Task title', { exact: true }).fill('Read chapter')
  await page.getByRole('button', { name: 'Add task', exact: true }).click()
  await page.getByRole('button', { name: 'Expand Read chapter', exact: true }).click()
  await page.getByLabel('Important', { exact: true }).check()
  await page.getByLabel('Read chapter name', { exact: true }).fill('Practice questions')
  await page.getByLabel('Practice questions notes').fill('Review mistakes')
  await page.getByRole('button', { name: 'Delete task', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Expand Practice questions', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Important', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Expand Practice questions', exact: true })).toBeVisible()
  await page.getByLabel('Search tasks').fill('missing')
  await expect(page.getByText('No matching tasks')).toBeVisible()
  await page.getByLabel('Search tasks').clear()
  await page.getByRole('button', { name: 'Expand Practice questions', exact: true }).click()
  await expect(page.getByLabel('Practice questions notes')).toHaveValue('Review mistakes')
  await page.screenshot({ path: 'test-results/home-expanded.png', fullPage: true })
})

test('disconnected inbox and account remain honest and navigable', async ({ page }) => {
  await page.route('**/api/v1/mail/snapshot', route => route.fulfill({status:401,json:{error:'Sign in required'}}))
  await page.goto('http://127.0.0.1:5173/')
  await page.getByRole('link', { name: 'Open inbox' }).click()
  await expect(page).toHaveURL(/\/inbox$/)
  await expect(page.getByRole('heading', { name: 'Inbox', exact: true })).toBeVisible()
  await expect(page.getByText('Sign in to sync email.', { exact: false })).toBeVisible()
  await page.screenshot({ path: 'test-results/inbox-expanded.png', fullPage: true })
  await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{configured:false,authenticated:false}}))
  await page.goto('http://127.0.0.1:5173/login')
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeDisabled()
  await page.screenshot({ path: 'test-results/login-expanded.png', fullPage: true })
  await page.getByRole('button', { name: 'Continue locally' }).click()
  await expect(page).toHaveURL(/\/$/)
})

test('daily actions keep checkoffs without a planned-date editor', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173/')
  await page.evaluate(() => localStorage.setItem('productivity-app.tasks.v1', JSON.stringify([{id:'past-task',title:'Earlier task',date:'2020-01-01',notes:'',completed:false}])))
  await page.reload()
  await expect(page.locator('.overdue-panel')).toHaveCount(0)
  await expect(page.locator('.day-summary')).toHaveCount(0)
  await page.evaluate(() => { const tasks=JSON.parse(localStorage.getItem('productivity-app.tasks.v1')!); const now=new Date(); tasks[0].date=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;localStorage.setItem('productivity-app.tasks.v1',JSON.stringify(tasks)) })
  await page.reload()
  await page.getByRole('button', {name:'Expand Earlier task', exact:true}).click()
  await expect(page.getByLabel('Earlier task date')).toHaveCount(0)
  await expect(page.getByText('Planned date', { exact: true })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Complete Earlier task' }).check()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Complete Earlier task' })).toBeChecked()
  await expect(page.getByRole('heading', { name: 'Daily plan', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/daily-plan.png', fullPage: true })
})

test('settings preferences persist and gear stays reachable', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173/')
  await expect(page.getByRole('button', { name: 'Account', exact:true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Settings', exact:true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await page.getByLabel('Display name', { exact:true }).fill('Daniel')
  await page.getByRole('button', { name:'Blue', exact:true }).click()
  await page.getByLabel('Reduce motion').check()
  await page.reload()
  await expect(page.getByLabel('Display name', { exact:true })).toHaveValue('Daniel')
  await expect(page.locator('html')).toHaveAttribute('data-theme','blue')
  await expect(page.getByLabel('Reduce motion')).toBeChecked()
  await expect(page.getByRole('button',{name:'Change password'})).toBeDisabled()
  await page.screenshot({path:'test-results/settings-desktop.png',fullPage:true})
  await page.setViewportSize({width:375,height:900})
  await expect(page.getByRole('button',{name:'Settings',exact:true})).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/settings-mobile.png',fullPage:true})
})
