import {test,expect} from '@playwright/test'
test('study plans share the task list, search, filters and empty state',async({page})=>{
 await page.clock.install({time:new Date('2026-10-03T12:00:00')})
 let actions=[30,45].map((minutes,i)=>({kind:'action',version:1,data:{id:String(i),preparationId:'prep',projectId:'p'+i,title:'Study step '+i,notes:'Logistic regression',minutes,date:'2026-10-03',completed:false,dismissed:false}}))
 await page.route('**/api/v1/planner/snapshot',r=>r.fulfill({json:{projects:[],actions,preparations:[{data:{id:'prep',title:'CSE354 M1'}}],status:{}}}))
 await page.route('**/api/v1/planner/entity',r=>{const change=r.request().postDataJSON();actions=actions.map(a=>a.data.id===change.data.id?{...a,data:change.data,version:a.version+1}:a);return r.fulfill({json:{code:200}})})
 await page.goto('http://127.0.0.1:5173')
 const list=page.locator('.task-list')
 await expect(list.getByRole('button',{name:'Study for CSE354 M1'})).toBeVisible()
 await expect(page.getByText('Hermes daily actions',{exact:true})).toHaveCount(0)
 await expect(page.getByText('No manual actions for this day')).toHaveCount(0)
 await page.getByLabel('Task title',{exact:true}).fill('Buy groceries')
 await page.getByRole('button',{name:'Add task',exact:true}).click()
 await expect(list.locator('.task-card')).toHaveCount(2)
 await page.getByLabel('Search tasks').fill('regression')
 await expect(list.locator('.task-card')).toHaveCount(1)
 await list.getByRole('button',{name:'Study for CSE354 M1'}).click()
 await expect(list.getByText('30 min',{exact:true})).toBeVisible()
 await page.getByLabel('Search tasks').fill('')
 await page.getByRole('button',{name:'Completed',exact:true}).click()
 await expect(list.getByText('No matching tasks')).toBeVisible()
 await page.getByRole('button',{name:'All',exact:true}).click()
 await list.getByRole('checkbox',{name:'Complete study for CSE354 M1'}).check()
 await page.getByRole('button',{name:'Completed',exact:true}).click()
 await expect(list.locator('.task-card')).toHaveCount(1)
 await expect(list.getByRole('button',{name:'Study for CSE354 M1'})).toBeVisible()
 await page.getByRole('button',{name:'All',exact:true}).click()
 await page.screenshot({path:'test-results/unified-tasks.png',fullPage:true})
})
